project:
  type: book

book:
  title: "WIPbook"
  date: "2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt

editor: visual

